routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('App\Http\Controllers')
    ->group(function(){
        Route::get('/', 'HomeController@index')->name('Home');
        Route::get('/about', 'HomeController@about')->name('About');
        Route::get('/contact', 'HomeController@contact')->name('Contact');
        // Route::get('/blog', 'BlogControllerNoAuth@blog')->name('Blog');
        Route::get('/mice', 'HomeController@mice')->name('Mice');
        Route::get('/visa-and-passport', 'HomeController@visaAndPassport')->name('VisaAndPassport');
        Route::get('/visa-and-passport/search', 'HomeController@visaAndPassportSearch')->name('VisaAndPassportSearch');
        Route::get('/faq', 'HomeController@faq')->name('Faq');
        Route::get('/tours', 'HomeController@toursOffer')->name('Tours');
        Route::get('/terms-and-conditions', 'HomeController@termsandconds')->name('TermsAndConditions');
        Route::get('/galleries', 'HomeController@galleries')->name('Gallery');
        Route::get('/attractions', 'HomeController@attractions')->name('Attractions');
        Route::get('/transportation', 'HomeController@transportation')->name('Transportation');
        Route::get('/careers', 'HomeController@careers')->name('Careers');
        Route::get('/section', 'HomeController@arrange')->name('Arrange');
    });

Route::prefix('products')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/', 'HomeController@products')->name('Products');
    Route::get('/travel-packages', 'ProductsController@travelPackages')->name('TravelPackagesPage');
    Route::get('/travel-packages-mice', 'ProductsController@travelMices')->name('TravelMicePage');
    Route::get('/staycations', 'ProductsController@staycations')->name('StaycationsPage');
    Route::get('/quarantine-hotels', 'ProductsController@quarantineHotels')->name('QuarantineHotelsPage');
    Route::get('/quarantine-hotels/search', 'ProductsController@qhSearch')->name('QuarantineHotelSearch');
    Route::get('/quarantine-hotels/sorting', 'ProductsController@qhSorting')->name('QuarantineHotelSorting');
});

Route::prefix('details')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/travel-packages/{slug}', 'DetailsController@index')->name('TravelPackagesDetails');
    Route::get('/quarantine-hotels/{slug}', 'DetailsController@quarantineHotels')->name('QuarantineHotelsDetails');
    Route::get('/careers/{slug}', 'DetailsController@careers')->name('CareersDetails');
});

Route::prefix('destinations')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/Europe', 'DestinationController@EuropeRegion')->name('EuropeRegion');
    Route::get('/Asia', 'DestinationController@AsiaRegion')->name('AsiaRegion');
    Route::get('/Indonesia', 'DestinationController@DomesticRegion')->name('DomesticRegion');
    Route::get('/America', 'DestinationController@AmericaRegion')->name('AmericaRegion');
    Route::get('/Australia', 'DestinationController@AustraliaRegion')->name('AustraliaRegion');
    Route::get('/Africa', 'DestinationController@AfricaRegion')->name('AfricaRegion');
    Route::get('/MiddleEast', 'DestinationController@MiddleEastRegion')->name('MiddleEastRegion');
    Route::get('/{categoryDestination}', 'DestinationController@DestinationCategory')->name('DestinationCategory');
});

Auth::routes();
Route::prefix('admin')
    ->namespace('App\Http\Controllers\Admin')
    ->middleware(['auth', 'admin'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')
            ->name('dashboard');
        Route::resource('travel-package', 'TravelPackageController');
        Route::get('travel-package-mice', 'TravelPackageController@indexMice')->name('travelMice');
        Route::resource('show-travel-package', 'ShowTravelPackageController');
        Route::resource('show-travel-package-mice', 'ShowTravelPackageMiceController');
        Route::resource('show-tour-events', 'ShowTourEventsController');
        Route::resource('destination-category', 'DestinationCategoryController');
        Route::resource('gallery', 'GalleryController');
        Route::resource('departure-date', 'DepartureDateController');
        Route::resource('trip-itineraries', 'TripItineraryController');
        Route::resource('inclusives', 'InclusiveController');
        Route::resource('staycation-ig-post', 'StaycationIgPostController');
        Route::resource('transportation', 'TransportationController');
        Route::resource('quarantine-hotel', 'HotelController');
        Route::resource('show-quarantine-hotel', 'ShowHotelsController');
        Route::resource('quarantine-hotel-room', 'HotelRoomTypeController');
        Route::resource('quarantine-hotel-price', 'HotelRoomPriceController');
        Route::resource('quarantine-hotel-gallery', 'HotelGalleryController');
        Route::resource('booking', 'BookingTourController');
        Route::get('booking/exportPDF/{id}', 'BookingTourController@exportPDF')->name('exportPDF');
        Route::resource('tour-offers', 'TourOfferController');
        Route::resource('sections', 'SectionController');
        Route::put('section/{section}', 'SectionController@updateCheckbox')->name('updateCheckbox');
        Route::resource('blog', 'BlogController');
        Route::resource('gallery-tour', 'GalleryTourController');
        Route::resource('flyer-image', 'FlyerImageController');
        Route::resource('slider-image', 'SliderImagesController');
        Route::resource('career', 'CareerController');
        Route::resource('visa-data', 'VisaDataController');
        Route::resource('vendor-data', 'VendorDataController');
        Route::resource('destination-data', 'DestinationDataController');
        Route::resource('type-data', 'TypeDataController');
    });
Route::prefix('superadmin')
    ->namespace('App\Http\Controllers\SuperAdmin')
    ->middleware(['auth', 'superadmin'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('superadmin.dashboard');
        Route::resource('admin', 'AdminController');
        Route::resource('sales', 'SalesController');
        Route::put('comition/approve1/{id}', 'CommitionController@approve1')->name('commition.approved1');
        Route::put('comition/approve2/{id}', 'CommitionController@approve2')->name('commition.approved2');
        Route::put('comition/approve3/{id}', 'CommitionController@approve3')->name('commition.approved3');
        Route::resource('commition', 'CommitionController');
        Route::resource('superadmin', 'SuperAdminController');
        Route::get('monitor/exportExcel/{id}', 'MonitoringController@exportExcel')->name('exportExcel');
        Route::get('monitor/exportInvoice/{id}', 'MonitoringController@exportInvoice')->name('exportInvoice');
        Route::get('monitor/confirmation', 'MonitoringController@confirmation')->name('monitor.confirmation');
        Route::put('monitor/approve/{id}', 'MonitoringController@approve')->name('monitor.approve');
        Route::put('monitor/invoiceSent/{id}', 'MonitoringController@invoiceSent')->name('monitor.invoiceSent');
        Route::put('monitor/paymentDone/{id}', 'MonitoringController@paymentDone')->name('monitor.paymentDone');
        Route::put('monitor/completed/{id}', 'MonitoringController@completed')->name('monitor.completed');
        Route::put('monitor/refund/{id}', 'MonitoringController@refund')->name('monitor.refund');
        Route::put('monitor/status/{id}', 'MonitoringController@updateStatus')->name('monitor.update.status');
        Route::resource('monitor', 'MonitoringController');
    });
Route::prefix('sales')
    ->namespace('App\Http\Controllers\Sales')
    ->middleware(['auth', 'sales'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('sales.dashboard');
        Route::as('sales.')->group(function(){
            Route::resource('sales', 'SalesController');
        });
        Route::resource('bookingtour', 'BookingTourController');
    });
Route::prefix('auth')
    ->group(function(){
        Route::get('/verify', function(){
            return view('auth.verify');
        })->name('verify');
    });

// Auth::routes(['verify' => true]);

// Route::get('/email/verify', function(){
//     return view('auth.verify-email');
// })->middleware('auth')->name('verification.notice');

// Route::get('/email/verify/{id}/{hash}', function(EmailVerificationRequest $request){
//     $request->fulfill();
//     return redirect('/');
// })->middleware(['auth', 'signed'])->name('verification.verify');

// Route::post('/email/verification-notification', function(Request $request){
//     $request->user()->sendEmailVerificationNotification();
//     return back()->with('message', 'Verification Link Sent!');
// })->middleware(['auth', 'throttle:6,1'])->name('verification.send');

app/Models/Transportation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transportation extends Model
{
    use HasFactory;

    protected $fillable = [
        'title', 'slug', 'type', 'capacity', 'price', 'note', 'image', 'region', 'is_availables'
    ];
}

app/Http/Controllers/Admin/TransportationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\TransportationEditRequest;
use App\Http\Requests\Admin\TransportationRequest;
use App\Models\Transportation;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use File;

class TransportationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transportation = Transportation::all()->sortByDesc('updated_at');
        return view('pages.admin.transportation.index', compact('transportation'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.transportation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TransportationRequest $request)
    {
        $data = $request->all();
        $file = $request->file('image');

        if ($file == '') {
            $request->image = '';
        }else{
            $imageName = $request->file('image')->getClientOriginalName();
            $request->image->move(public_path('storage/assets/transportation/'), $imageName);
            $data['image'] = 'assets/transportation/' . $imageName;
        }
        
        $data['title'] = $request->title;
        $data['slug'] = Str::slug($request->title);
        $data['type'] = $request->type;
        $data['capacity'] = $request->capacity;
        $data['price'] = str_replace(',', '', $request->price);
        $data['note'] = $request->note;
        $data['region'] = $request->region;
        $data['is_available'] = $request->is_available;

        Transportation::create($data);

        return redirect()->route('transportation.index')->with('success', 'Data Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Transportation::find($id);
        return view('pages.admin.transportation.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TransportationEditRequest $request, $id)
    {
        $data = $request->all();
        $file = $request->file('image');
        $transportation = Transportation::find($id);

        if ($file == '') {
            $request->image = $transportation->image;
        }else{
            $deletePath = public_path('storage/'.$transportation->image);
            if(File::exists($deletePath)) {
                File::delete($deletePath);
            }
            $imageName = $request->file('image')->getClientOriginalName();
            $request->image->move(public_path('storage/assets/transportation/'), $imageName);
            $data['image'] = 'assets/transportation/' . $imageName;
        }
        
        $data['title'] = $request->title;
        $data['slug'] = Str::slug($request->title);
        $data['type'] = $request->type;
        $data['capacity'] = $request->capacity;
        $data['price'] = str_replace(',', '', $request->price);
        $data['note'] = $request->note;
        $data['region'] = $request->region;
        $data['is_available'] = $request->is_available;

        $transportation->update($data);

        return redirect()->route('transportation.index')->with('success', 'Data Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transportation = Transportation::find($id);
        $deletePath = public_path('storage/'. $transportation->image);
        if(File::exists($deletePath)){
            File::delete($deletePath);
        }

        $transportation->delete();
        return redirect()->route('transportation.index')->with('success', 'Data Deleted');
    }
}

resources/views/pages/admin/transportation/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Transportation | daysOff Official Website</title>
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add New Transportation</h1>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="card shadow">
            <div class="card-body">
                <form action="{{route('transportation.store')}}" method="post" enctype="multipart/form-data">
                @csrf

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Title" value="{{old('title')}}" required>
                    <small class="form-text text-muted">(TIDAK BOLEH DOUBLE!)</small>
                </div>

                <div class="row form-group">
                    <div class="col-sm-3">
                        <label>Type</label>
                        <select class="form-control select2" name="type">
                            <option disabled selected>Choose One</option>
                            <option value="Car">Car</option>
                            <option value="Bus">Bus</option>
                        </select>
                    </div>

                    <div class="col-sm-3">
                        <label for="capacity">Capacity</label>
                        <input type="number" class="form-control" min="0" name="capacity" id="capacity" placeholder="Capacity" value="{{ old('capacity') }}">
                    </div>
                    
                    <div class="col-sm-3">
                        <label for="region">Region</label>
                        <input type="text" class="form-control" name="region" placeholder="Region" value="{{old('region')}}">
                        <small class="form-text text-muted">Lokasi dalam bahasa inggris (Sebutkan 1 saja daerah, e.g. Europe; Middle-East; Indonesia; etc.)</small>
                    </div>

                    <div class="col-sm-3">
                        <label for="price">Price (IDR)</label>
                        <input type="text" class="form-control" name="price" id="price" placeholder="Transportation Price" value="{{old('price')}}">
                        <small class="form-text text-muted">Masukkan harga (DALAM IDR, ANGKA SAJA)</small>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="note">Note</label>
                        <input type="text" class="form-control" name="note" placeholder="note" value="{{old('note')}}">
                        <small class="form-text text-muted">Ex: Toll & Parkir Included</small>
                    </div>

                    <div class="col-sm-6">
                        <label for="image">Image</label>
                        <input type="file" class="form-control" name="image" id="image" placeholder="Image">
                        <small class="form-text text-muted">Upload file .jpg atau .png</small>
                        <img src="#" width="200px" class="rounded mx-auto d-block" id="preview-img" style="visibility: hidden;">
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="status">Transportation Status</label><br>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_available" id="is_available0" value="0">
                            <label class="form-check-label" for="is_available0">Not Available</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_available" id="is_available1" value="1">
                            <label class="form-check-label" for="is_available1">Available</label>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Save</button>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

@push('custom-script')
<script>
    $(document).on('keyup', '#price', function(event) {
        if(event.which >= 37 && event.which <= 40) return;

        // format number
        $(this).val(function(index, value) {
        return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        });
    });
</script>
<script>
    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview-img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#image").change(function(){
        $('#preview-img').css('visibility', 'visible');
        previewImage(this);
    });
</script>
@endpush

resources/views/pages/admin/transportation/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Transportation | daysOff Official Website</title>
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Transportation {{$item->title}}</h1>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="card shadow mb-4">
            <div class="card-body">
                <form action="{{route('transportation.update', $item->id)}}" method="post" enctype="multipart/form-data">
                @method('PUT')
                @csrf

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Title" value="{{$item->title}}" required>
                    <small class="form-text text-muted">(TIDAK BOLEH DOUBLE!)</small>
                </div>
                <div class="row form-group">
                    <div class="col-sm-3">
                        <label>Type</label>
                        <select class="form-control select2" name="type">
                            <option disabled selected>Choose One</option>
                            <option value="Car" @if($item->type == 'Car') selected @endif>Car</option>
                            <option value="Bus" @if($item->type == 'Bus') selected @endif>Bus</option>
                        </select>
                    </div>

                    <div class="col-sm-3">
                        <label for="capacity">Capacity</label>
                        <input type="number" class="form-control" min="0" name="capacity" id="capacity" placeholder="Capacity" value="{{ $item->capacity }}">
                    </div>
                    
                    <div class="col-sm-3">
                        <label for="region">Region</label>
                        <input type="text" class="form-control" name="region" placeholder="Region" value="{{ $item->region }}">
                        <small class="form-text text-muted">Lokasi dalam bahasa inggris (Sebutkan 1 saja daerah, e.g. Europe; Middle-East; Indonesia; etc.)</small>
                    </div>

                    <div class="col-sm-3">
                        <label for="price">Price (IDR)</label>
                        <input type="text" class="form-control" name="price" id="price" placeholder="Transportation Price" value="{{ $item->price }}">
                        <small class="form-text text-muted">Masukkan harga (DALAM IDR, ANGKA SAJA)</small>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="note">Note</label>
                        <input type="text" class="form-control" name="note" placeholder="note" value="{{ $item->note }}">
                        <small class="form-text text-muted">Ex: Toll & Parkir Included</small>
                    </div>

                    <div class="col-sm-6">
                        <label for="image">Image</label>
                        <input type="file" name="image" id="image" class="form-control">
                        <small class="form-text text-muted">Upload file .jpg atau .png</small>
                        <img src="{{ Storage::url($item->image) }}" width="200px" class="rounded mx-auto d-block" id="preview-img">
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="status">Transportation Status</label><br>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_available" id="is_available0" value="0" @if($item->is_available == 0) checked @endif>
                            <label class="form-check-label" for="is_available0">Not Available</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_available" id="is_available1" value="1" @if($item->is_available == 1) checked @endif>
                            <label class="form-check-label" for="is_available1">Available</label>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

@push('custom-script')
<script>
    $(document).on('keyup', '#price', function(event) {
        if(event.which >= 37 && event.which <= 40) return;

        // format number
        $(this).val(function(index, value) {
        return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        });
    });
</script>
<script>
    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview-img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#image").change(function(){
        previewImage(this);
    });
</script>
@endpush

resources/views/pages/admin/transportation/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Transportation | daysOff Official Website</title>
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Transportation</h1>
            <a href="{{route('transportation.create')}}" class="btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Add New
            </a>
        </div>

        <div class="row">
            <div class="card-body">
                <div class="table-responsive">
                @if ($message = session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ $message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                    <table class="table" id="myTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Transportation Name</th>
                                <th>Type</th>
                                <th>Region</th>
                                <th>Price</th>
                                <th>Note</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($transportation as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->title }}</td>
                                <td>{{ $item->type }}</td>
                                <td>{{ $item->region }}</td>
                                <td>Rp{{ number_format($item->price) }}</td>
                                <td>{{ $item->note }}</td>
                                <td class="text-center">
                                    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#detail{{ $item->id }}"><i class="fa fa-eye"></i></button>
                                    <a href="{{route('transportation.edit', $item->id)}}" class="btn btn-outline-success" title="edit">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <form action="{{route('transportation.destroy', $item->id)}}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-outline-danger" onclick="return confirm('Are you sure you want to delete {{ $item->title }}?');" title="delete">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        @foreach($transportation as $item)
        <!-- Detail Modal -->
        <div class="modal fade" id="detail{{ $item->id }}" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Title</th>
                                    <td>{{ $item->title }}</td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td>{{ $item->type }}</td>
                                </tr>
                                <tr>
                                    <th>Capacity</th>
                                    <td>{{ $item->capacity }}</td>
                                </tr>
                                <tr>
                                    <th>Region</th>
                                    <td>{{ $item->region }}</td>
                                </tr>
                                <tr>
                                    <th>Price</th>
                                    <td>Rp{{ number_format($item->price) }}</td>
                                </tr>
                                <tr>
                                    <th>Note</th>
                                    <td>{{ $item->note }}</td>
                                </tr>
                                <tr>
                                    <th>Image</th>
                                    <td><img src="{{ Storage::url($item->image) }}" width="200px" class="rounded mx-auto d-block"></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        @if($item->is_available == 0)
                                            <p class="text-danger">Not Available</p>
                                        @else
                                            <p class="text-success">Available</p>
                                        @endif
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
    <!-- /.container-fluid -->
@endsection