routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('App\Http\Controllers')
    ->group(function(){
        Route::get('/', 'HomeController@index')->name('Home');
        Route::get('/about', 'HomeController@about')->name('About');
        Route::get('/contact', 'HomeController@contact')->name('Contact');
        // Route::get('/blog', 'BlogControllerNoAuth@blog')->name('Blog');
        Route::get('/mice', 'HomeController@mice')->name('Mice');
        Route::get('/visa-and-passport', 'HomeController@visaAndPassport')->name('VisaAndPassport');
        Route::get('/visa-and-passport/search', 'HomeController@visaAndPassportSearch')->name('VisaAndPassportSearch');
        Route::get('/faq', 'HomeController@faq')->name('Faq');
        Route::get('/tours', 'HomeController@toursOffer')->name('Tours');
        Route::get('/terms-and-conditions', 'HomeController@termsandconds')->name('TermsAndConditions');
        Route::get('/galleries', 'HomeController@galleries')->name('Gallery');
        Route::get('/attractions', 'HomeController@attractions')->name('Attractions');
        Route::get('/transportation', 'HomeController@transportation')->name('Transportation');
        Route::get('/careers', 'HomeController@careers')->name('Careers');
        Route::get('/section', 'HomeController@arrange')->name('Arrange');
    });

Route::prefix('products')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/', 'HomeController@products')->name('Products');
    Route::get('/travel-packages', 'ProductsController@travelPackages')->name('TravelPackagesPage');
    Route::get('/travel-packages-mice', 'ProductsController@travelMices')->name('TravelMicePage');
    Route::get('/staycations', 'ProductsController@staycations')->name('StaycationsPage');
    Route::get('/quarantine-hotels', 'ProductsController@quarantineHotels')->name('QuarantineHotelsPage');
    Route::get('/quarantine-hotels/search', 'ProductsController@qhSearch')->name('QuarantineHotelSearch');
    Route::get('/quarantine-hotels/sorting', 'ProductsController@qhSorting')->name('QuarantineHotelSorting');
});

Route::prefix('details')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/travel-packages/{slug}', 'DetailsController@index')->name('TravelPackagesDetails');
    Route::get('/quarantine-hotels/{slug}', 'DetailsController@quarantineHotels')->name('QuarantineHotelsDetails');
    Route::get('/careers/{slug}', 'DetailsController@careers')->name('CareersDetails');
});

Route::prefix('destinations')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/Europe', 'DestinationController@EuropeRegion')->name('EuropeRegion');
    Route::get('/Asia', 'DestinationController@AsiaRegion')->name('AsiaRegion');
    Route::get('/Indonesia', 'DestinationController@DomesticRegion')->name('DomesticRegion');
    Route::get('/America', 'DestinationController@AmericaRegion')->name('AmericaRegion');
    Route::get('/Australia', 'DestinationController@AustraliaRegion')->name('AustraliaRegion');
    Route::get('/Africa', 'DestinationController@AfricaRegion')->name('AfricaRegion');
    Route::get('/MiddleEast', 'DestinationController@MiddleEastRegion')->name('MiddleEastRegion');
    Route::get('/{categoryDestination}', 'DestinationController@DestinationCategory')->name('DestinationCategory');
});

Auth::routes();
Route::prefix('admin')
    ->namespace('App\Http\Controllers\Admin')
    ->middleware(['auth', 'admin'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')
            ->name('dashboard');
        Route::resource('travel-package', 'TravelPackageController');
        Route::get('travel-package-mice', 'TravelPackageController@indexMice')->name('travelMice');
        Route::resource('show-travel-package', 'ShowTravelPackageController');
        Route::resource('show-travel-package-mice', 'ShowTravelPackageMiceController');
        Route::resource('show-tour-events', 'ShowTourEventsController');
        Route::resource('destination-category', 'DestinationCategoryController');
        Route::resource('gallery', 'GalleryController');
        Route::resource('departure-date', 'DepartureDateController');
        Route::resource('trip-itineraries', 'TripItineraryController');
        Route::resource('inclusives', 'InclusiveController');
        Route::resource('staycation-ig-post', 'StaycationIgPostController');
        Route::resource('transportation', 'TransportationController');
        Route::resource('quarantine-hotel', 'HotelController');
        Route::resource('show-quarantine-hotel', 'ShowHotelsController');
        Route::resource('quarantine-hotel-room', 'HotelRoomTypeController');
        Route::resource('quarantine-hotel-price', 'HotelRoomPriceController');
        Route::resource('quarantine-hotel-gallery', 'HotelGalleryController');
        Route::resource('booking', 'BookingTourController');
        Route::get('booking/exportPDF/{id}', 'BookingTourController@exportPDF')->name('exportPDF');
        Route::resource('tour-offers', 'TourOfferController');
        Route::resource('sections', 'SectionController');
        Route::put('section/{section}', 'SectionController@updateCheckbox')->name('updateCheckbox');
        Route::resource('blog', 'BlogController');
        Route::resource('gallery-tour', 'GalleryTourController');
        Route::resource('flyer-image', 'FlyerImageController');
        Route::resource('slider-image', 'SliderImagesController');
        Route::resource('career', 'CareerController');
        Route::resource('visa-data', 'VisaDataController');
        Route::resource('vendor-data', 'VendorDataController');
        Route::resource('destination-data', 'DestinationDataController');
        Route::resource('type-data', 'TypeDataController');
    });
Route::prefix('superadmin')
    ->namespace('App\Http\Controllers\SuperAdmin')
    ->middleware(['auth', 'superadmin'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('superadmin.dashboard');
        Route::resource('admin', 'AdminController');
        Route::resource('sales', 'SalesController');
        Route::put('comition/approve1/{id}', 'CommitionController@approve1')->name('commition.approved1');
        Route::put('comition/approve2/{id}', 'CommitionController@approve2')->name('commition.approved2');
        Route::put('comition/approve3/{id}', 'CommitionController@approve3')->name('commition.approved3');
        Route::resource('commition', 'CommitionController');
        Route::resource('superadmin', 'SuperAdminController');
        Route::get('monitor/exportExcel/{id}', 'MonitoringController@exportExcel')->name('exportExcel');
        Route::get('monitor/exportInvoice/{id}', 'MonitoringController@exportInvoice')->name('exportInvoice');
        Route::get('monitor/confirmation', 'MonitoringController@confirmation')->name('monitor.confirmation');
        Route::put('monitor/approve/{id}', 'MonitoringController@approve')->name('monitor.approve');
        Route::put('monitor/invoiceSent/{id}', 'MonitoringController@invoiceSent')->name('monitor.invoiceSent');
        Route::put('monitor/paymentDone/{id}', 'MonitoringController@paymentDone')->name('monitor.paymentDone');
        Route::put('monitor/completed/{id}', 'MonitoringController@completed')->name('monitor.completed');
        Route::put('monitor/refund/{id}', 'MonitoringController@refund')->name('monitor.refund');
        Route::put('monitor/status/{id}', 'MonitoringController@updateStatus')->name('monitor.update.status');
        Route::resource('monitor', 'MonitoringController');
    });
Route::prefix('sales')
    ->namespace('App\Http\Controllers\Sales')
    ->middleware(['auth', 'sales'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('sales.dashboard');
        Route::as('sales.')->group(function(){
            Route::resource('sales', 'SalesController');
        });
        Route::resource('bookingtour', 'BookingTourController');
    });
Route::prefix('auth')
    ->group(function(){
        Route::get('/verify', function(){
            return view('auth.verify');
        })->name('verify');
    });

// Auth::routes(['verify' => true]);

// Route::get('/email/verify', function(){
//     return view('auth.verify-email');
// })->middleware('auth')->name('verification.notice');

// Route::get('/email/verify/{id}/{hash}', function(EmailVerificationRequest $request){
//     $request->fulfill();
//     return redirect('/');
// })->middleware(['auth', 'signed'])->name('verification.verify');

// Route::post('/email/verification-notification', function(Request $request){
//     $request->user()->sendEmailVerificationNotification();
//     return back()->with('message', 'Verification Link Sent!');
// })->middleware(['auth', 'throttle:6,1'])->name('verification.send');

resources/views/pages/admin/quarantine-hotel/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Quarantine Hotel | daysOff Official Website</title>
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Tambah Hotel Karantina</h1>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="card shadow">
            <div class="card-body">
                <form action="{{route('quarantine-hotel.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="hotel_name">Hotel Name</label>
                    <input type="text" class="form-control" name="hotel_name" placeholder="Hotel Name" value="{{old('hotel_name')}}">
                    <small class="form-text text-muted">Nama Hotel Karantina</small>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="hotel_address">Address</label>
                        <input type="text" class="form-control" name="hotel_address" placeholder="Address" value="{{old('hotel_address')}}">
                        <small class="form-text text-muted">Alamat Hotel Karantina (e.g. Jl. Kebayoran Lama)</small>
                    </div>

                    <div class="col-sm-6">
                        <label for="hotel_city">City</label>
                        <input type="text" class="form-control" name="hotel_city" placeholder="City" value="{{old('hotel_city')}}">
                        <small class="form-text text-muted">Lokasi Hotel Karantina dalam Bahasa Inggris (Sebutkan 1 saja daerah, e.g. Tangerang, Bekasi.)</small>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-3">
                        <label for="hotel_rate">Rate</label>
                        <input type="number" class="form-control" name="hotel_rate" min="1" max="5" value="{{old('hotel_rate')}}">
                        <small class="form-text text-muted">Rating Hotel Karantina (Minimal 1 dan Maksimal 5)</small>
                    </div>
                    <div class="col-sm-3">
                        <label for="chse_score">CHSE Score</label>
                        <input type="number" class="form-control" name="chse_score" min="1" max="100" value="{{old('chse_score')}}">
                        <small class="form-text text-muted">(Minimal 1 dan Maksimal 100)</small>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label for="name">Description :</label>
                        <textarea class="ckeditor form-control" name="description" value="description"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="hotel_status">Status Hotel</label><br>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="hotel_status" id="hotel_status0" value="0">
                        <label class="form-check-label" for="hotel_status1">
                        Not Available
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="hotel_status" id="hotel_status1" value="1">
                        <label class="form-check-label" for="hotel_status1">
                        Available
                        </label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Save</button>
                </form>
            </div>
        </div>
    </div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/admin/quarantine-hotel/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Quarantine Hotel | daysOff Official Website</title>
@endsection

@section('content')

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Hotel Karantina {{$item->hotel_name}}</h1>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="card shadow mb-4">
            <div class="card-body">
                <form action="{{route('quarantine-hotel.update', $item->id)}}" method="post" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="hotel_name">Hotel Name</label>
                    <input type="text" class="form-control" name="hotel_name" placeholder="Hotel Name" value="{{$item->hotel_name}}">
                    <small class="form-text text-muted">Nama Hotel Karantina</small>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="hotel_address">Address</label>
                        <input type="text" class="form-control" name="hotel_address" placeholder="Address" value="{{$item->hotel_address}}">
                        <small class="form-text text-muted">Alamat Hotel Karantina (e.g. Jl. Kebayoran Lama)</small>
                    </div>

                    <div class="col-sm-6">
                        <label for="hotel_city">City</label>
                        <input type="text" class="form-control" name="hotel_city" placeholder="City" value="{{$item->hotel_city}}">
                        <small class="form-text text-muted">Lokasi Hotel Karantina dalam Bahasa Inggris (Sebutkan 1 saja daerah, e.g. Tangerang, Bekasi.)</small>
                    </div>
                </div>
                <div class="row form-group ">
                    <div class="col-sm-3">
                        <label for="hotel_rate">Rate</label>
                        <input type="number" class="form-control" name="hotel_rate" min="1" max="5" value="{{$item->hotel_rate}}">
                        <small class="form-text text-muted">Rating Hotel Karantina (Minimal 1 dan Maksimal 5)</small>
                    </div>
                    <div class="col-sm-3">
                        <label for="chse_score">CHSE Score</label>
                        <input type="number" class="form-control" name="chse_score" min="1" max="100" value="{{$item->chse_score}}">
                        <small class="form-text text-muted">(Minimal 1 dan Maksimal 100)</small>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label for="name">Description :</label>
                        <textarea class="ckeditor form-control" name="description" value="description">{{$item->description}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="hotel_status">Status Hotel</label><br>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="hotel_status" id="hotel_status0" value="0" @if ($item->hotel_status == '0') checked @endif>
                        <label class="form-check-label" for="hotel_status0">
                        Not Available
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="hotel_status" id="hotel_status1" value="1" @if ($item->hotel_status == '1') checked @endif>
                        <label class="form-check-label" for="hotel_status1">
                        Available
                        </label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/admin/quarantine-hotel/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Quarantine Hotel | daysOff Official Website</title>
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Hotel Karantina</h1>
            <a href="{{route('quarantine-hotel.create')}}" class="btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Add New
            </a>
        </div>

        <div class="row">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="myTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Hotel Name</th>
                                <th>Address</th>
                                <th>City</th>
                                <th>Image Total</th>
                                <th>Rate</th>
                                <th>CHSE</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($items as $item)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$item->hotel_name}}</td>
                                <td>{{$item->hotel_address}}</td>
                                <td>{{$item->hotel_city}}</td>
                                <td>
                                    @if($item->hotelGalleries->count()>0)
                                        {{$item->hotelGalleries->count()}}<br>
                                    @else
                                        0
                                    @endif
                                </td>
                                <td>{{$item->hotel_rate}}</td>
                                <td>{{$item->chse_score}}</td>

                                @if($item->hotel_status!=0)
                                    <td> <h6><span class="badge badge-info">Available</span></h6> </td>
                                @else
                                    <td> <h6><span class="badge badge-danger">Not Available</span></h6></td>
                                @endif

                                <td class="text-center">
                                    <a href="{{route('QuarantineHotelsDetails', $item->slug)}}" class="btn btn-outline-info btn-sm" title="view">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{route('quarantine-hotel.edit', $item->id)}}" class="btn btn-outline-success btn-sm" title="edit">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <form action="{{route('quarantine-hotel.destroy', $item->id)}}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure you want to delete {{ $item->hotel_name }}?');" title="delete">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="14" class="text-center">Belum Ada Data Hotel Karantina</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<!-- /.container-fluid -->
@endsection