routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('App\Http\Controllers')
    ->group(function(){
        Route::get('/', 'HomeController@index')->name('Home');
        Route::get('/about', 'HomeController@about')->name('About');
        Route::get('/contact', 'HomeController@contact')->name('Contact');
        // Route::get('/blog', 'BlogControllerNoAuth@blog')->name('Blog');
        Route::get('/mice', 'HomeController@mice')->name('Mice');
        Route::get('/visa-and-passport', 'HomeController@visaAndPassport')->name('VisaAndPassport');
        Route::get('/visa-and-passport/search', 'HomeController@visaAndPassportSearch')->name('VisaAndPassportSearch');
        Route::get('/faq', 'HomeController@faq')->name('Faq');
        Route::get('/tours', 'HomeController@toursOffer')->name('Tours');
        Route::get('/terms-and-conditions', 'HomeController@termsandconds')->name('TermsAndConditions');
        Route::get('/galleries', 'HomeController@galleries')->name('Gallery');
        Route::get('/attractions', 'HomeController@attractions')->name('Attractions');
        Route::get('/transportation', 'HomeController@transportation')->name('Transportation');
        Route::get('/careers', 'HomeController@careers')->name('Careers');
        Route::get('/section', 'HomeController@arrange')->name('Arrange');
    });

Route::prefix('products')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/', 'HomeController@products')->name('Products');
    Route::get('/travel-packages', 'ProductsController@travelPackages')->name('TravelPackagesPage');
    Route::get('/travel-packages-mice', 'ProductsController@travelMices')->name('TravelMicePage');
    Route::get('/staycations', 'ProductsController@staycations')->name('StaycationsPage');
    Route::get('/quarantine-hotels', 'ProductsController@quarantineHotels')->name('QuarantineHotelsPage');
    Route::get('/quarantine-hotels/search', 'ProductsController@qhSearch')->name('QuarantineHotelSearch');
    Route::get('/quarantine-hotels/sorting', 'ProductsController@qhSorting')->name('QuarantineHotelSorting');
});

Route::prefix('details')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/travel-packages/{slug}', 'DetailsController@index')->name('TravelPackagesDetails');
    Route::get('/quarantine-hotels/{slug}', 'DetailsController@quarantineHotels')->name('QuarantineHotelsDetails');
    Route::get('/careers/{slug}', 'DetailsController@careers')->name('CareersDetails');
});

Route::prefix('destinations')
->namespace('App\Http\Controllers')
->group(function(){
    Route::get('/Europe', 'DestinationController@EuropeRegion')->name('EuropeRegion');
    Route::get('/Asia', 'DestinationController@AsiaRegion')->name('AsiaRegion');
    Route::get('/Indonesia', 'DestinationController@DomesticRegion')->name('DomesticRegion');
    Route::get('/America', 'DestinationController@AmericaRegion')->name('AmericaRegion');
    Route::get('/Australia', 'DestinationController@AustraliaRegion')->name('AustraliaRegion');
    Route::get('/Africa', 'DestinationController@AfricaRegion')->name('AfricaRegion');
    Route::get('/MiddleEast', 'DestinationController@MiddleEastRegion')->name('MiddleEastRegion');
    Route::get('/{categoryDestination}', 'DestinationController@DestinationCategory')->name('DestinationCategory');
});

Auth::routes();
Route::prefix('admin')
    ->namespace('App\Http\Controllers\Admin')
    ->middleware(['auth', 'admin'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')
            ->name('dashboard');
        Route::resource('travel-package', 'TravelPackageController');
        Route::get('travel-package-mice', 'TravelPackageController@indexMice')->name('travelMice');
        Route::resource('show-travel-package', 'ShowTravelPackageController');
        Route::resource('show-travel-package-mice', 'ShowTravelPackageMiceController');
        Route::resource('show-tour-events', 'ShowTourEventsController');
        Route::resource('destination-category', 'DestinationCategoryController');
        Route::resource('gallery', 'GalleryController');
        Route::resource('departure-date', 'DepartureDateController');
        Route::resource('trip-itineraries', 'TripItineraryController');
        Route::resource('inclusives', 'InclusiveController');
        Route::resource('staycation-ig-post', 'StaycationIgPostController');
        Route::resource('transportation', 'TransportationController');
        Route::resource('quarantine-hotel', 'HotelController');
        Route::resource('show-quarantine-hotel', 'ShowHotelsController');
        Route::resource('quarantine-hotel-room', 'HotelRoomTypeController');
        Route::resource('quarantine-hotel-price', 'HotelRoomPriceController');
        Route::resource('quarantine-hotel-gallery', 'HotelGalleryController');
        Route::resource('booking', 'BookingTourController');
        Route::get('booking/exportPDF/{id}', 'BookingTourController@exportPDF')->name('exportPDF');
        Route::resource('tour-offers', 'TourOfferController');
        Route::resource('sections', 'SectionController');
        Route::put('section/{section}', 'SectionController@updateCheckbox')->name('updateCheckbox');
        Route::resource('blog', 'BlogController');
        Route::resource('gallery-tour', 'GalleryTourController');
        Route::resource('flyer-image', 'FlyerImageController');
        Route::resource('slider-image', 'SliderImagesController');
        Route::resource('career', 'CareerController');
        Route::resource('visa-data', 'VisaDataController');
        Route::resource('vendor-data', 'VendorDataController');
        Route::resource('destination-data', 'DestinationDataController');
        Route::resource('type-data', 'TypeDataController');
    });
Route::prefix('superadmin')
    ->namespace('App\Http\Controllers\SuperAdmin')
    ->middleware(['auth', 'superadmin'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('superadmin.dashboard');
        Route::resource('admin', 'AdminController');
        Route::resource('sales', 'SalesController');
        Route::put('comition/approve1/{id}', 'CommitionController@approve1')->name('commition.approved1');
        Route::put('comition/approve2/{id}', 'CommitionController@approve2')->name('commition.approved2');
        Route::put('comition/approve3/{id}', 'CommitionController@approve3')->name('commition.approved3');
        Route::resource('commition', 'CommitionController');
        Route::resource('superadmin', 'SuperAdminController');
        Route::get('monitor/exportExcel/{id}', 'MonitoringController@exportExcel')->name('exportExcel');
        Route::get('monitor/exportInvoice/{id}', 'MonitoringController@exportInvoice')->name('exportInvoice');
        Route::get('monitor/confirmation', 'MonitoringController@confirmation')->name('monitor.confirmation');
        Route::put('monitor/approve/{id}', 'MonitoringController@approve')->name('monitor.approve');
        Route::put('monitor/invoiceSent/{id}', 'MonitoringController@invoiceSent')->name('monitor.invoiceSent');
        Route::put('monitor/paymentDone/{id}', 'MonitoringController@paymentDone')->name('monitor.paymentDone');
        Route::put('monitor/completed/{id}', 'MonitoringController@completed')->name('monitor.completed');
        Route::put('monitor/refund/{id}', 'MonitoringController@refund')->name('monitor.refund');
        Route::put('monitor/status/{id}', 'MonitoringController@updateStatus')->name('monitor.update.status');
        Route::resource('monitor', 'MonitoringController');
    });
Route::prefix('sales')
    ->namespace('App\Http\Controllers\Sales')
    ->middleware(['auth', 'sales'])
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('sales.dashboard');
        Route::as('sales.')->group(function(){
            Route::resource('sales', 'SalesController');
        });
        Route::resource('bookingtour', 'BookingTourController');
    });
Route::prefix('auth')
    ->group(function(){
        Route::get('/verify', function(){
            return view('auth.verify');
        })->name('verify');
    });

// Auth::routes(['verify' => true]);

// Route::get('/email/verify', function(){
//     return view('auth.verify-email');
// })->middleware('auth')->name('verification.notice');

// Route::get('/email/verify/{id}/{hash}', function(EmailVerificationRequest $request){
//     $request->fulfill();
//     return redirect('/');
// })->middleware(['auth', 'signed'])->name('verification.verify');

// Route::post('/email/verification-notification', function(Request $request){
//     $request->user()->sendEmailVerificationNotification();
//     return back()->with('message', 'Verification Link Sent!');
// })->middleware(['auth', 'throttle:6,1'])->name('verification.send');

app/Models/SliderImages.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SliderImages extends Model
{
    use HasFactory;

    protected $table = 'slider_images';

    protected $guarded = ['
        id
    '];
}

app/Http/Controllers/Admin/SliderImagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\SliderImages;
use File;

class SliderImagesController extends Controller
{
    public function __construct(){

    }
    
    public function index()
    {
        $sliderImage = SliderImages::all();

        return view('pages.admin.slider-image.index', [
            'sliderImage' => $sliderImage
        ]);
    }

    public function create(){
        return view('pages.admin.slider-image.create');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $file = $request->file('slider_image');

        if ($file == '') {
            $data['image_url'] = '';
        }else{
            $imageName = $request->file('slider_image')->getClientOriginalName();
            $request->slider_image->move(public_path('storage/assets/slider-image/'), $imageName);
            $data['image_url'] = 'assets/slider-image/' . $imageName;
        }

        SliderImages::create($data);

        return redirect()->route('slider-image.index');
    }

    public function edit($id)
    {
        $sliderImage = SliderImages::findOrFail($id);

        return view('pages.admin.slider-image.edit', [
            'sliderImage' => $sliderImage
        ]);
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $sliderImage = SliderImages::findOrFail($id);

        $file = $request->file('slider_image');

        if ($file == '') {
            $data['slider_image'] = $sliderImage->image_url;
            return redirect()->route('flyer-image.index');
        } else {
            $deletePath = public_path('storage/'.$sliderImage->image_url);
            if(File::exists($deletePath)) {
                $deleteImage = File::delete($deletePath);
            }
            $imageName = $request->file('slider_image')->getClientOriginalName();
            $uploadImage = $request->slider_image->move(public_path('storage/assets/slider-image/'), $imageName);
            $data['image_url'] = 'assets/slider-image/' . $imageName;
        }
        
        $update = $sliderImage->update($data);

        return redirect()->route('slider-image.index')->with('success', 'Slider Image Update Success');
    }

    public function destroy($id){
        $slider = SliderImages::findOrFail($id);
        $deletePath = public_path('storage/'.$slider->image_url);

        if(File::exists($deletePath)) {
            File::delete($deletePath);
        }

        SliderImages::destroy($id);
        return redirect()->route('slider-image.index');
    }
}

resources/views/pages/admin/slider-image/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Add Slider Image | daysOff Official Website</title>
@endsection

@section('content')
    
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Add Slider Image</h1>
                    </div>

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <form action="{{route('slider-image.store')}}" method="post"
                                enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="image">Slider Image</label></br>
                                <input type="file" class="form-control" name="slider_image" id="image" placeholder="Image" required>
                                <small class="form-text text-muted">Upload file .jpg dengan size ca. 1920px x 940px (Edit ukuran pake canva atau sejenisnya)</small>
                                <img src="#" width="200px" class="rounded mx-auto d-block" id="preview-img" style="visibility: hidden;">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
@endsection

@push('custom-script')
<script>
    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview-img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#image").change(function(){
        $('#preview-img').css('visibility', 'visible');
        previewImage(this);
    });
</script>
@endpush

resources/views/pages/admin/slider-image/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Edit Slider Image | daysOff Official Website</title>
@endsection

@section('content')
    
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Edit Slider Image</h1>
                    </div>

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <form action="{{route('slider-image.update', $sliderImage->id)}}" method="post"
                                enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <label for="image">Slider Image</label></br>
                                <input type="file" class="form-control" name="slider_image" id="image" placeholder="Image">
                                <small class="form-text text-muted">Upload file .jpg dengan size ca. 1920px x 940px (Edit ukuran pake canva atau sejenisnya)</small>
                                <img src="{{ Storage::url($sliderImage->image_url) }}" width="200px" class="rounded mx-auto d-block" id="preview-img">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
@endsection

@push('custom-script')
<script> 
    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview-img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#image").change(function(){
        previewImage(this);
    });
</script>
@endpush

resources/views/pages/admin/slider-image/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Slider Image | daysOff Official Website</title>
@endsection

@section('content')
    
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Slider Image</h1>
            <a href="{{route('slider-image.create')}}" class="btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Add New
            </a>
        </div>

        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
        @endif
        @if (session('success'))
        <div class="alert alert-success">
            <ul>
                <li>{{ session('success') }}</li>
            </ul>
        </div>
        @endif

        <div class="row">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="myTable" class="table" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($sliderImage as $sliderImages)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>
                                    <img src="{{url('storage/'.$sliderImages->image_url)}}" style="width: 200px" class="img-thumbnail" alt="{{$sliderImages->image_url}}" />
                                </td>
                                <td class="text-center">
                                    <a href="{{route('slider-image.edit', $sliderImages->id)}}" class="btn btn-outline-success">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <form action="{{route('slider-image.destroy', $sliderImages->id)}}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-outline-danger" onclick="return confirm('Are you sure you want to delete this?');">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="4" class="text-center">Belum Ada Slider Image</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>



    </div>
    <!-- /.container-fluid -->

@endsection